---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: accounts-service
- name: accounts-version

outputs:
- name: build

params:
  TERM: dumb

run:
  path: accounts-service/ci/build.sh
